export type WorkOrderStatus = "Open" | "In Progress" | "Complete" | "Overdue" | "On Hold";

export interface WorkOrder {
  id: string;
  woNumber: string;
  partNumber: string;
  partName: string;
  customer: string;
  quantity: number;
  dueDate: string;
  startDate: string;
  status: WorkOrderStatus;
  priority: "Low" | "Medium" | "High" | "Critical";
  progress: number;
  laborHours: number;
  estimatedHours: number;
  materialCost: number;
  laborCost: number;
  notes: string;
}

export const workOrders: WorkOrder[] = [
  {
    id: "wo-001",
    woNumber: "WO-2024-0891",
    partNumber: "MED-4521-A",
    partName: "Titanium Hip Implant — Left",
    customer: "Stryker Medical",
    quantity: 12,
    dueDate: "2024-03-22",
    startDate: "2024-03-08",
    status: "In Progress",
    priority: "High",
    progress: 65,
    laborHours: 18.5,
    estimatedHours: 28,
    materialCost: 4200,
    laborCost: 1480,
    notes: "Surface finish inspection required before final delivery",
  },
  {
    id: "wo-002",
    woNumber: "WO-2024-0892",
    partNumber: "SURG-0033-B",
    partName: "Surgical Clamp Handle",
    customer: "Medtronic",
    quantity: 50,
    dueDate: "2024-03-18",
    startDate: "2024-03-05",
    status: "Overdue",
    priority: "Critical",
    progress: 40,
    laborHours: 22,
    estimatedHours: 35,
    materialCost: 1850,
    laborCost: 1760,
    notes: "Material delay from supplier — expedite alternative",
  },
  {
    id: "wo-003",
    woNumber: "WO-2024-0893",
    partNumber: "CARD-1102-C",
    partName: "Cardiac Device Housing",
    customer: "Abbott Labs",
    quantity: 8,
    dueDate: "2024-03-28",
    startDate: "2024-03-12",
    status: "Open",
    priority: "Medium",
    progress: 0,
    laborHours: 0,
    estimatedHours: 42,
    materialCost: 9600,
    laborCost: 0,
    notes: "Awaiting first article approval",
  },
  {
    id: "wo-004",
    woNumber: "WO-2024-0894",
    partNumber: "ORTH-0887-A",
    partName: "Knee Brace Bracket",
    customer: "Zimmer Biomet",
    quantity: 30,
    dueDate: "2024-03-20",
    startDate: "2024-03-01",
    status: "Complete",
    priority: "Low",
    progress: 100,
    laborHours: 16,
    estimatedHours: 18,
    materialCost: 2100,
    laborCost: 1280,
    notes: "Shipped 2024-03-19",
  },
  {
    id: "wo-005",
    woNumber: "WO-2024-0895",
    partNumber: "NEURO-3301-D",
    partName: "Neuro Electrode Array",
    customer: "Boston Scientific",
    quantity: 4,
    dueDate: "2024-04-02",
    startDate: "2024-03-15",
    status: "In Progress",
    priority: "High",
    progress: 30,
    laborHours: 8,
    estimatedHours: 26,
    materialCost: 14200,
    laborCost: 640,
    notes: "Cleanroom processing required — schedule Room A",
  },
  {
    id: "wo-006",
    woNumber: "WO-2024-0896",
    partNumber: "DENT-0021-B",
    partName: "Dental Drill Body",
    customer: "Dentsply Sirona",
    quantity: 100,
    dueDate: "2024-04-10",
    startDate: "2024-03-18",
    status: "Open",
    priority: "Low",
    progress: 0,
    laborHours: 0,
    estimatedHours: 55,
    materialCost: 3400,
    laborCost: 0,
    notes: "",
  },
  {
    id: "wo-007",
    woNumber: "WO-2024-0897",
    partNumber: "ENDO-5500-A",
    partName: "Endoscope Distal Tip",
    customer: "Karl Storz",
    quantity: 20,
    dueDate: "2024-03-25",
    startDate: "2024-03-10",
    status: "In Progress",
    priority: "Medium",
    progress: 75,
    laborHours: 24,
    estimatedHours: 32,
    materialCost: 6800,
    laborCost: 1920,
    notes: "Final polishing step in queue",
  },
  {
    id: "wo-008",
    woNumber: "WO-2024-0898",
    partNumber: "SPIN-2211-C",
    partName: "Spinal Fusion Cage",
    customer: "NuVasive",
    quantity: 6,
    dueDate: "2024-04-05",
    startDate: "2024-03-19",
    status: "On Hold",
    priority: "Medium",
    progress: 15,
    laborHours: 4,
    estimatedHours: 38,
    materialCost: 8900,
    laborCost: 320,
    notes: "On hold pending engineering change order approval",
  },
  {
    id: "wo-009",
    woNumber: "WO-2024-0899",
    partNumber: "VASC-0041-A",
    partName: "Vascular Stent Mold Insert",
    customer: "Cook Medical",
    quantity: 2,
    dueDate: "2024-03-30",
    startDate: "2024-03-14",
    status: "In Progress",
    priority: "High",
    progress: 50,
    laborHours: 12,
    estimatedHours: 24,
    materialCost: 3100,
    laborCost: 960,
    notes: "CMM inspection scheduled Friday",
  },
  {
    id: "wo-010",
    woNumber: "WO-2024-0900",
    partNumber: "DIAG-7700-B",
    partName: "Diagnostic Probe Housing",
    customer: "Philips Healthcare",
    quantity: 25,
    dueDate: "2024-04-15",
    startDate: "2024-03-22",
    status: "Open",
    priority: "Low",
    progress: 0,
    laborHours: 0,
    estimatedHours: 30,
    materialCost: 4500,
    laborCost: 0,
    notes: "",
  },
];

export const workOrderRoutingSteps = [
  { step: 1, operation: "Raw Material Inspection", machine: "CMM Station", status: "Complete", hours: 0.5 },
  { step: 2, operation: "CNC Turning — OD Profile", machine: "Haas ST-30", status: "Complete", hours: 3.5 },
  { step: 3, operation: "CNC Milling — Features", machine: "Haas UMC-500", status: "In Progress", hours: 5.0 },
  { step: 4, operation: "Deburring & Edge Break", machine: "Manual Station 2", status: "Open", hours: 1.0 },
  { step: 5, operation: "Surface Finish — Passivation", machine: "Chem Tank B", status: "Open", hours: 2.0 },
  { step: 6, operation: "Final CMM Inspection", machine: "Zeiss CMM", status: "Open", hours: 1.5 },
  { step: 7, operation: "Packaging & Labeling", machine: "Packaging Station", status: "Open", hours: 0.5 },
];
